# Generated by Django 3.0.2 on 2020-01-28 12:31

from django.db import migrations, models
import django.db.models.deletion
from peminjaman.models import validate_file_extension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_peminjaman', models.CharField(max_length=20)),
                ('nip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegawai.TambahPegawai')),
                ('nama_pegawai', models.CharField(max_length=100, null=True, blank=True)),
                ('tanggal_pinjam', models.DateField()),
                ('tanggal_kembali', models.DateField()),
                ('bast_disposisi', models.FileField(upload_to='peminjaman/', validators=[validate_file_extension])),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
