# Generated by Django 3.0.2 on 2020-01-28 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peminjaman', '0001_initial'),
        ('barang', '0001_initial'),
        ('gedung', '0001_initial'),
        ('ruang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPeminjaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_peminjaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peminjaman.Peminjaman')),
                ('kode_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.TabelBarang')),
                ('nama_barang', models.CharField(max_length=100, null=True, blank=True)),
                ('jumlah', models.IntegerField()),
                ('status', models.CharField(choices=[('Siap', 'Siap'), ('Tidak Siap', 'Tidak Siap'),], max_length=50)),
                ('gedung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gedung.TambahGedung')),
                ('ruang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruang.TambahRuang')),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
